on:
  schedule:
    - cron: '0 0 * * *' # every 12 hours
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update README.md stats
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.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 }}
    - name: Update README.md with latest stats
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config arieladimitria github-actions[bot]
        git config arieladimitria 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git pull --rebase
        git push
        fi
